"""Unit and hook-script tests for `.claude/hooks/sessionstart_board_context.py` (TASK-037):
injects `BOARD.md`'s `In Progress`/`In Review` regions, an in-flight task summary, and
`.tasks/guidelines.md` into `SessionStart`'s `additionalContext`.

Acceptance criteria this covers:
- no in-flight task -> board's open columns only
- an in-flight task -> also its id/title/status/pr
- `guidelines.md`'s contents appear alongside the board state
- silent (no output) if `.tasks/` doesn't exist
- still works (board context, no guidelines section) if `.tasks/` exists but `guidelines.md`
  doesn't
"""

import importlib.util
import json
import subprocess
import sys
from importlib.machinery import SourceFileLoader
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT_PATH = REPO_ROOT / ".claude" / "hooks" / "sessionstart_board_context.py"

_loader = SourceFileLoader("sessionstart_board_context", str(SCRIPT_PATH))
_spec = importlib.util.spec_from_loader("sessionstart_board_context", _loader)
sessionstart_board_context = importlib.util.module_from_spec(_spec)
sys.modules["sessionstart_board_context"] = sessionstart_board_context
_loader.exec_module(sessionstart_board_context)


_BOARD_TEMPLATE = (
    "# Board\n\n"
    "## In Progress\n\n"
    "<!-- BEGIN:in-progress (generated by sync — do not edit) -->\n{in_progress}\n<!-- END:in-progress -->\n\n"
    "## In Review\n\n"
    "<!-- BEGIN:in-review (generated by sync — do not edit) -->\n{in_review}\n<!-- END:in-review -->\n"
)

_TASK_TEMPLATE = (
    "---\nid: {id}\ntitle: {title}\nstatus: {status}\nepic: null\n"
    "branch: {branch}\npr: {pr}\nblocked_by: []\nblocks: []\n---\n"
)


def _write_board(tasks_root: Path, in_progress: str = "_(none)_", in_review: str = "_(none)_") -> None:
    (tasks_root / "BOARD.md").write_text(_BOARD_TEMPLATE.format(in_progress=in_progress, in_review=in_review))


def _write_task(tasks_root: Path, task_id: str, title: str, status: str, branch: str, pr: str | None = None) -> None:
    pr_value = "null" if pr is None else f'"{pr}"'
    (tasks_root / f"{task_id}-{title.lower().replace(' ', '-')}.md").write_text(
        _TASK_TEMPLATE.format(id=task_id, title=title, status=status, branch=f'"{branch}"', pr=pr_value)
    )


def _sync_bin(tasks_root: Path) -> None:
    """A real, minimal copy of `.tasks/bin/sync` so `_load_sync` can load it -- copying the
    actual file keeps this test honest against the real region/discover implementation rather
    than a hand-rolled stand-in.
    """
    (tasks_root / "bin").mkdir(parents=True, exist_ok=True)
    (tasks_root / "bin" / "sync").write_text((REPO_ROOT / ".tasks" / "bin" / "sync").read_text())


# ---------------------------------------------------------------------------
# build_context -- pure
# ---------------------------------------------------------------------------


def test_build_context_none_when_tasks_dir_absent(tmp_path):
    assert sessionstart_board_context.build_context(tmp_path / ".tasks") is None


def test_build_context_includes_board_columns_with_no_in_flight_task(tmp_path):
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    _sync_bin(tasks_root)
    _write_board(tasks_root)
    context = sessionstart_board_context.build_context(tasks_root)
    assert "### In Progress" in context
    assert "### In Review" in context
    assert "## Current task" not in context


def test_build_context_includes_current_task_summary_when_in_progress(tmp_path):
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    _sync_bin(tasks_root)
    _write_board(tasks_root, in_progress="| TASK-001 | a | — | task-001-a |")
    _write_task(tasks_root, "TASK-001", "a", "in-progress", branch="task-001-a")
    context = sessionstart_board_context.build_context(tasks_root)
    assert "## Current task" in context
    assert "- id: TASK-001" in context
    assert "- status: in-progress" in context
    assert "- pr: none yet" in context


def test_build_context_includes_pr_when_in_review(tmp_path):
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    _sync_bin(tasks_root)
    _write_board(tasks_root, in_review="| TASK-002 | b | — | https://example.com/pr/2 |")
    _write_task(
        tasks_root, "TASK-002", "b", "in-review", branch="task-002-b", pr="https://example.com/pr/2"
    )
    context = sessionstart_board_context.build_context(tasks_root)
    assert "- status: in-review" in context
    assert "- pr: https://example.com/pr/2" in context


def test_build_context_includes_guidelines_verbatim(tmp_path):
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    _sync_bin(tasks_root)
    _write_board(tasks_root)
    (tasks_root / "guidelines.md").write_text("# Workflow guidelines\n\nSome specific text.\n")
    context = sessionstart_board_context.build_context(tasks_root)
    assert "## Workflow guidelines (.tasks/guidelines.md)" in context
    assert "Some specific text." in context


def test_build_context_omits_guidelines_section_when_absent_but_keeps_board(tmp_path):
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    _sync_bin(tasks_root)
    _write_board(tasks_root, in_progress="| TASK-003 | c | — | task-003-c |")
    _write_task(tasks_root, "TASK-003", "c", "in-progress", branch="task-003-c")
    context = sessionstart_board_context.build_context(tasks_root)
    assert "Workflow guidelines" not in context
    assert "### In Progress" in context
    assert "## Current task" in context


def test_build_context_none_when_tasks_dir_exists_but_is_entirely_empty(tmp_path):
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    assert sessionstart_board_context.build_context(tasks_root) is None


# ---------------------------------------------------------------------------
# main() -- hook-script, real subprocess
# ---------------------------------------------------------------------------


def _payload(cwd: str, hook_event_name: str = "SessionStart", source: str = "startup") -> dict:
    return {
        "session_id": "test-session", "cwd": cwd, "hook_event_name": hook_event_name, "source": source,
    }


def _run_hook(payload: dict) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT_PATH)], input=json.dumps(payload), capture_output=True, text=True
    )


def test_hook_silent_when_tasks_dir_absent(tmp_path):
    result = _run_hook(_payload(str(tmp_path)))
    assert result.returncode == 0
    assert result.stdout == ""
    assert result.stderr == ""


def test_hook_ignores_a_non_session_start_event(tmp_path):
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    _sync_bin(tasks_root)
    _write_board(tasks_root, in_progress="| TASK-001 | a | — | task-001-a |")
    result = _run_hook(_payload(str(tmp_path), hook_event_name="PreToolUse"))
    assert result.returncode == 0
    assert result.stdout == ""


def test_hook_survives_malformed_json_on_stdin():
    result = subprocess.run(
        [sys.executable, str(SCRIPT_PATH)], input="not json", capture_output=True, text=True
    )
    assert result.returncode == 0
    assert result.stdout == ""


def test_hook_output_matches_the_documented_session_start_schema(tmp_path):
    """The exact shape Claude Code's `SessionStart` hooks are documented to emit:
    `{"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": <str>}}`,
    and nothing else on stdout (stdout must contain only the JSON object).
    """
    tasks_root = tmp_path / ".tasks"
    tasks_root.mkdir()
    _sync_bin(tasks_root)
    _write_board(tasks_root, in_progress="| TASK-001 | a | — | task-001-a |")
    _write_task(tasks_root, "TASK-001", "a", "in-progress", branch="task-001-a")
    result = _run_hook(_payload(str(tmp_path)))
    assert result.returncode == 0
    parsed = json.loads(result.stdout)
    assert set(parsed.keys()) == {"hookSpecificOutput"}
    hook_output = parsed["hookSpecificOutput"]
    assert hook_output["hookEventName"] == "SessionStart"
    assert isinstance(hook_output["additionalContext"], str)
    assert "TASK-001" in hook_output["additionalContext"]


# ---------------------------------------------------------------------------
# Real repo tree
# ---------------------------------------------------------------------------


def test_hook_against_this_repos_real_tree_reports_the_workflow_guidelines():
    result = _run_hook(_payload(str(REPO_ROOT)))
    assert result.returncode == 0
    parsed = json.loads(result.stdout)
    context = parsed["hookSpecificOutput"]["additionalContext"]
    assert "## Board state" in context
    assert "## Workflow guidelines (.tasks/guidelines.md)" in context


# ---------------------------------------------------------------------------
# Vendoring: the shipped copy must never silently drift from its canonical source
# ---------------------------------------------------------------------------


def test_vendored_hook_script_is_byte_identical_to_the_canonical_one():
    vendored = (
        REPO_ROOT / ".claude" / "skills" / "init-project" / "vendored-hooks" / "sessionstart_board_context.py"
    )
    assert vendored.read_bytes() == SCRIPT_PATH.read_bytes()


def test_settings_json_template_registers_sessionstart_the_same_way_as_this_repos_own():
    template = json.loads(
        (REPO_ROOT / ".claude" / "skills" / "init-project" / "templates" / "settings.json").read_text()
    )
    canonical = json.loads((REPO_ROOT / ".claude" / "settings.json").read_text())
    assert template["hooks"]["SessionStart"] == canonical["hooks"]["SessionStart"]
