"""Unit and hook-script tests for `.tasks/bin/guardrails.py`'s structural-edit checks and the
`PreToolUse`/`Edit|Write` hook that calls them (TASK-033).

Acceptance criteria this covers:
- an `Edit`/`Write` whose target range falls inside any generated region is denied
- an epic frontmatter edit changing `status` to anything but `wont-do` is denied
- edits outside both cases are unaffected
- the vendored copy of the hook script stays byte-identical to its canonical source
"""

import json
import subprocess
import sys
from pathlib import Path

import guardrails

REPO_ROOT = Path(__file__).resolve().parent.parent
HOOK_SCRIPT = REPO_ROOT / ".claude" / "hooks" / "pretooluse_edit_write.py"


# ---------------------------------------------------------------------------
# region_edit_violation -- pure, against text fixtures
# ---------------------------------------------------------------------------

EPIC_TEXT = (
    "---\nid: EPIC-001\ntitle: MVP\nspec: SPEC-001\nstatus: in-progress\n---\n\n"
    "## Goal\n\nSome prose here, outside any region.\n\n"
    "<!-- BEGIN:children (generated by sync — do not edit) -->\n"
    "| Task | Status | Title |\n|---|---|---|\n"
    "| TASK-001 | done | a |\n"
    "\n"
    "Progress: 1/1 done\n"
    "<!-- END:children -->\n"
)

BOARD_TEXT = (
    "# Board\n\n"
    "## Epics\n\n"
    "<!-- BEGIN:epics (generated by sync — do not edit) -->\n"
    "| Epic | Status | Progress |\n|---|---|---|\n"
    "| EPIC-001 | in-progress | 1/2 done |\n"
    "<!-- END:epics -->\n\n"
    "## TODO\n\n- TASK-002 — b\n\n"
    "## In Progress\n\n"
    "<!-- BEGIN:in-progress (generated by sync — do not edit) -->\n_(none)_\n<!-- END:in-progress -->\n\n"
    "## Done\n\n"
    "<!-- BEGIN:done (generated by sync — do not edit) -->\n_(none)_\n<!-- END:done -->\n"
)


def test_region_edit_violation_none_when_region_content_is_unchanged():
    new_text = EPIC_TEXT.replace("Some prose here", "Some *different* prose here")
    assert guardrails.region_edit_violation("EPIC-001-x.md", EPIC_TEXT, new_text) is None


def test_region_edit_violation_flags_a_changed_region_body():
    new_text = EPIC_TEXT.replace("| TASK-001 | done | a |", "| TASK-001 | done | a hand-edited row |")
    assert guardrails.region_edit_violation("EPIC-001-x.md", EPIC_TEXT, new_text) == "children"


def test_region_edit_violation_flags_removed_markers():
    new_text = EPIC_TEXT.replace(
        "<!-- BEGIN:children (generated by sync — do not edit) -->\n"
        "| Task | Status | Title |\n|---|---|---|\n"
        "| TASK-001 | done | a |\n"
        "\n"
        "Progress: 1/1 done\n"
        "<!-- END:children -->\n",
        "",
    )
    assert guardrails.region_edit_violation("EPIC-001-x.md", EPIC_TEXT, new_text) == "children"


def test_region_edit_violation_identifies_the_right_board_region():
    new_text = BOARD_TEXT.replace("_(none)_\n<!-- END:done -->", "| TASK-099 | x | y | z |\n<!-- END:done -->")
    assert guardrails.region_edit_violation("BOARD.md", BOARD_TEXT, new_text) == "done"


def test_region_edit_violation_none_for_todo_edits():
    # TODO is hand-maintained, never a BEGIN/END region -- editing it is never a violation here.
    new_text = BOARD_TEXT.replace("- TASK-002 — b", "- TASK-002 — b (reordered)")
    assert guardrails.region_edit_violation("BOARD.md", BOARD_TEXT, new_text) is None


def test_region_edit_violation_none_for_a_file_with_no_known_regions():
    assert guardrails.region_edit_violation("TASK-001-x.md", "---\nid: TASK-001\n---\nbody\n", "different\n") is None


# ---------------------------------------------------------------------------
# epic_status_edit_violation -- pure, against text fixtures
# ---------------------------------------------------------------------------


def test_epic_status_edit_violation_none_when_unchanged():
    assert guardrails.epic_status_edit_violation("EPIC-001-x.md", EPIC_TEXT, EPIC_TEXT) is None


def test_epic_status_edit_violation_flags_a_hand_set_status():
    new_text = EPIC_TEXT.replace("status: in-progress", "status: done")
    assert guardrails.epic_status_edit_violation("EPIC-001-x.md", EPIC_TEXT, new_text) == "done"


def test_epic_status_edit_violation_allows_wont_do():
    new_text = EPIC_TEXT.replace("status: in-progress", "status: wont-do")
    assert guardrails.epic_status_edit_violation("EPIC-001-x.md", EPIC_TEXT, new_text) is None


def test_epic_status_edit_violation_none_for_non_epic_files():
    old_task = "---\nid: TASK-001\nstatus: todo\n---\n"
    new_task = "---\nid: TASK-001\nstatus: done\n---\n"
    assert guardrails.epic_status_edit_violation("TASK-001-x.md", old_task, new_task) is None


def test_epic_status_edit_violation_none_on_unparseable_frontmatter():
    assert guardrails.epic_status_edit_violation("EPIC-001-x.md", EPIC_TEXT, "not frontmatter at all") is None


# ---------------------------------------------------------------------------
# check_region_edit / check_epic_status_edit / evaluate_edit_write -- tool_input level
# ---------------------------------------------------------------------------


def test_check_region_edit_allows_a_new_file(tmp_path):
    result = guardrails.check_region_edit(
        "Write", {"file_path": str(tmp_path / "EPIC-001-x.md"), "content": EPIC_TEXT}, tmp_path
    )
    assert result.allow is True


def test_check_region_edit_denies_write_that_changes_region_content(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    new_text = EPIC_TEXT.replace("| TASK-001 | done | a |", "| TASK-001 | done | hand-edited |")
    result = guardrails.check_region_edit("Write", {"file_path": str(path), "content": new_text}, tmp_path)
    assert result.allow is False
    assert "children" in result.reason


def test_check_region_edit_allows_an_edit_outside_the_region(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    result = guardrails.check_region_edit(
        "Edit",
        {"file_path": str(path), "old_string": "## Goal", "new_string": "## Goal (renamed)"},
        tmp_path,
    )
    assert result.allow is True


def test_check_region_edit_denies_an_edit_inside_the_region(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    result = guardrails.check_region_edit(
        "Edit",
        {"file_path": str(path), "old_string": "Progress: 1/1 done", "new_string": "Progress: 2/2 done"},
        tmp_path,
    )
    assert result.allow is False


def test_check_region_edit_allows_when_old_string_not_found(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    result = guardrails.check_region_edit(
        "Edit", {"file_path": str(path), "old_string": "nonexistent text", "new_string": "x"}, tmp_path
    )
    assert result.allow is True


def test_check_epic_status_edit_denies_a_hand_set_status(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    result = guardrails.check_epic_status_edit(
        "Edit", {"file_path": str(path), "old_string": "status: in-progress", "new_string": "status: done"}, tmp_path
    )
    assert result.allow is False
    assert "'done'" in result.reason


def test_check_epic_status_edit_allows_wont_do(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    result = guardrails.check_epic_status_edit(
        "Edit",
        {"file_path": str(path), "old_string": "status: in-progress", "new_string": "status: wont-do"},
        tmp_path,
    )
    assert result.allow is True


def test_evaluate_edit_write_allows_an_unrelated_edit(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    result = guardrails.evaluate_edit_write(
        "Edit", {"file_path": str(path), "old_string": "## Goal", "new_string": "## Goal!"}, tmp_path
    )
    assert result.allow is True


def test_evaluate_edit_write_ignores_other_tools(tmp_path):
    result = guardrails.evaluate_edit_write("Read", {"file_path": "whatever"}, tmp_path)
    assert result.allow is True


# ---------------------------------------------------------------------------
# The hook script itself, as a real subprocess -- the documented `PreToolUse` stdin shape
# ---------------------------------------------------------------------------


def _run_hook(payload: dict) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(HOOK_SCRIPT)], input=json.dumps(payload), capture_output=True, text=True
    )


def _payload(tool_name: str, tool_input: dict, cwd: str) -> dict:
    return {
        "session_id": "test-session", "cwd": cwd, "hook_event_name": "PreToolUse",
        "tool_name": tool_name, "tool_input": tool_input,
    }


def test_hook_script_denies_an_edit_inside_a_generated_region(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    payload = _payload(
        "Edit",
        {"file_path": str(path), "old_string": "Progress: 1/1 done", "new_string": "Progress: 2/2 done"},
        str(tmp_path),
    )
    result = _run_hook(payload)
    assert result.returncode == 2
    assert "children" in result.stderr


def test_hook_script_denies_an_epic_status_hand_set_via_write(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    new_text = EPIC_TEXT.replace("status: in-progress", "status: todo")
    payload = _payload("Write", {"file_path": str(path), "content": new_text}, str(tmp_path))
    result = _run_hook(payload)
    assert result.returncode == 2
    assert "'todo'" in result.stderr


def test_hook_script_allows_wont_do_via_write(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    new_text = EPIC_TEXT.replace("status: in-progress", "status: wont-do")
    payload = _payload("Write", {"file_path": str(path), "content": new_text}, str(tmp_path))
    result = _run_hook(payload)
    assert result.returncode == 0
    assert result.stdout == ""
    assert result.stderr == ""


def test_hook_script_allows_an_edit_outside_any_region(tmp_path):
    path = tmp_path / "EPIC-001-x.md"
    path.write_text(EPIC_TEXT)
    payload = _payload(
        "Edit", {"file_path": str(path), "old_string": "## Goal", "new_string": "## Goal (renamed)"}, str(tmp_path)
    )
    result = _run_hook(payload)
    assert result.returncode == 0
    assert result.stdout == ""


def test_hook_script_ignores_non_edit_write_tool_calls():
    result = _run_hook(_payload("Bash", {"command": "ls"}, "/nonexistent"))
    assert result.returncode == 0
    assert result.stdout == ""


# ---------------------------------------------------------------------------
# Vendoring
# ---------------------------------------------------------------------------


def test_vendored_edit_write_hook_is_byte_identical_to_the_canonical_one():
    vendored = REPO_ROOT / ".claude" / "skills" / "init-project" / "vendored-hooks" / "pretooluse_edit_write.py"
    assert vendored.read_bytes() == HOOK_SCRIPT.read_bytes()
