"""Unit tests for `.tasks/bin/sync`'s generated-region engine (TASK-005).

Acceptance criteria this covers:
- find_region: span or None; tolerates extra text in the BEGIN comment
- replace_region: swaps only the inter-marker lines; no-op when already correct
- ensure_region: appends BEGIN/body/END at the anchor when absent
- rendering: no leading blank line after BEGIN, single trailing newline
  before END, `_(none)_` for an empty body
- missing region, empty region, region with content, two regions in one
  file, and the idempotent-replace case
"""

import pytest

from sync import RegionError, RegionSpan, ensure_region, find_region, replace_region

ONE_REGION = (
    "# Doc\n\n"
    "<!-- BEGIN:epics (generated by sync — do not edit) -->\n"
    "| Epic | Status |\n"
    "|---|---|\n"
    "| EPIC-001 | todo |\n"
    "<!-- END:epics -->\n"
)

TWO_REGIONS = (
    "# Board\n\n"
    "## Epics\n\n"
    "<!-- BEGIN:epics (generated by sync — do not edit) -->\n"
    "| Epic | Status |\n"
    "|---|---|\n"
    "| EPIC-001 | todo |\n"
    "<!-- END:epics -->\n\n"
    "## Done\n\n"
    "<!-- BEGIN:done (generated by sync — do not edit) -->\n"
    "_(none)_\n"
    "<!-- END:done -->\n"
)


# ---------------------------------------------------------------------------
# find_region
# ---------------------------------------------------------------------------


def test_find_region_returns_none_when_absent():
    assert find_region("# Doc\n\nno markers here\n", "epics") is None


def test_find_region_locates_the_span():
    span = find_region(ONE_REGION, "epics")
    assert isinstance(span, RegionSpan)
    content = ONE_REGION[span.begin_end:span.end_start]
    assert content == "| Epic | Status |\n|---|---|\n| EPIC-001 | todo |\n"


def test_find_region_tolerates_extra_text_in_begin_comment():
    text = "<!-- BEGIN:x anything at all here -->\nbody\n<!-- END:x -->\n"
    span = find_region(text, "x")
    assert span is not None
    assert text[span.begin_end:span.end_start] == "body\n"


def test_find_region_finds_the_right_region_among_two():
    epics_span = find_region(TWO_REGIONS, "epics")
    done_span = find_region(TWO_REGIONS, "done")
    assert TWO_REGIONS[epics_span.begin_end:epics_span.end_start] == (
        "| Epic | Status |\n|---|---|\n| EPIC-001 | todo |\n"
    )
    assert TWO_REGIONS[done_span.begin_end:done_span.end_start] == "_(none)_\n"
    assert epics_span.end_end <= done_span.begin_start


def test_find_region_raises_on_begin_without_matching_end():
    with pytest.raises(RegionError, match="no matching END"):
        find_region("<!-- BEGIN:x -->\nbody\n", "x")


def test_find_region_raises_on_unclosed_begin_line():
    with pytest.raises(RegionError, match="not closed with '-->'"):
        find_region("<!-- BEGIN:x no closing marker\nbody\n<!-- END:x -->\n", "x")


def test_find_region_does_not_match_a_different_name():
    text = "<!-- BEGIN:epics2 -->\nbody\n<!-- END:epics2 -->\n"
    assert find_region(text, "epics") is None


# ---------------------------------------------------------------------------
# replace_region
# ---------------------------------------------------------------------------


def test_replace_region_swaps_only_the_inter_marker_lines():
    result = replace_region(ONE_REGION, "epics", "| Epic | Status |\n|---|---|\n| EPIC-002 | done |")
    assert result == (
        "# Doc\n\n"
        "<!-- BEGIN:epics (generated by sync — do not edit) -->\n"
        "| Epic | Status |\n"
        "|---|---|\n"
        "| EPIC-002 | done |\n"
        "<!-- END:epics -->\n"
    )


def test_replace_region_only_touches_the_named_region():
    new_epics = replace_region(TWO_REGIONS, "epics", "changed")
    assert "changed" in new_epics
    # the 'done' region's content is untouched
    done_span = find_region(new_epics, "done")
    assert new_epics[done_span.begin_end:done_span.end_start] == "_(none)_\n"


def test_replace_region_renders_empty_body_as_none_marker():
    result = replace_region(ONE_REGION, "epics", "")
    span = find_region(result, "epics")
    assert result[span.begin_end:span.end_start] == "_(none)_\n"


def test_replace_region_no_leading_blank_line_and_single_trailing_newline():
    result = replace_region(ONE_REGION, "epics", "line one\nline two")
    span = find_region(result, "epics")
    content = result[span.begin_end:span.end_start]
    assert not content.startswith("\n")  # no leading blank line after BEGIN
    assert content == "line one\nline two\n"  # exactly one trailing newline before END


def test_replace_region_is_a_true_no_op_when_unchanged():
    once = replace_region(ONE_REGION, "epics", "| Epic | Status |\n|---|---|\n| EPIC-001 | todo |")
    twice = replace_region(once, "epics", "| Epic | Status |\n|---|---|\n| EPIC-001 | todo |")
    assert twice == once
    assert twice is once  # identity, not just equality — a genuine no-op


def test_replace_region_raises_when_region_missing():
    with pytest.raises(RegionError, match="no BEGIN:missing"):
        replace_region(ONE_REGION, "missing", "x")


# ---------------------------------------------------------------------------
# ensure_region
# ---------------------------------------------------------------------------


def test_ensure_region_delegates_to_replace_when_present():
    result = ensure_region(ONE_REGION, "epics", "new body")
    span = find_region(result, "epics")
    assert result[span.begin_end:span.end_start] == "new body\n"


def test_ensure_region_appends_at_end_when_absent_and_no_anchor():
    text = "# Doc\n\nsome prose.\n"
    result = ensure_region(text, "epics", "content")
    assert result.startswith(text)
    span = find_region(result, "epics")
    assert span is not None
    assert result[span.begin_end:span.end_start] == "content\n"


def test_ensure_region_adds_newline_before_appending_if_missing():
    text = "# Doc with no trailing newline"
    result = ensure_region(text, "epics", "content")
    assert result.startswith(text + "\n<!-- BEGIN:epics")


def test_ensure_region_inserts_at_the_given_anchor():
    text = "# Board\n\n## Epics\n\n## Done\n\n<!-- BEGIN:done -->\n_(none)_\n<!-- END:done -->\n"
    result = ensure_region(text, "epics", "row here", anchor="## Epics\n\n")
    assert result == (
        "# Board\n\n## Epics\n\n"
        "<!-- BEGIN:epics (generated by sync — do not edit) -->\n"
        "row here\n"
        "<!-- END:epics -->\n"
        "## Done\n\n<!-- BEGIN:done -->\n_(none)_\n<!-- END:done -->\n"
    )


def test_ensure_region_raises_when_anchor_not_found():
    with pytest.raises(RegionError, match="anchor not found"):
        ensure_region("# Doc\n", "epics", "x", anchor="## Nope\n\n")


def test_ensure_region_empty_body_renders_none_marker_on_first_creation():
    result = ensure_region("# Doc\n", "epics", "")
    span = find_region(result, "epics")
    assert result[span.begin_end:span.end_start] == "_(none)_\n"


def test_ensure_region_is_idempotent_once_created():
    once = ensure_region("# Doc\n", "epics", "content")
    twice = ensure_region(once, "epics", "content")
    assert twice == once
