"""Unit tests for `.tasks/bin/sync check` (TASK-012).

Acceptance criteria this covers:
- writes no files, ever
- exit 0 / no output on a clean repo; exit non-zero with a unified diff
  per file when something differs
- covers every generated region (epic children, spec epics, board epics
  panel, the four columns), the TODO merge, and epic status frontmatter
- diff output names the file and region
- unit tests: a clean repo (exit 0), a repo with one hand-broken region
  (exit non-zero, diff points at it)
"""

from pathlib import Path

from sync import compute_mismatches, run_check


def write_clean_repo(root: Path) -> None:
    """A minimal but internally-consistent .tasks/ tree: one spec, one
    epic (with a done and a todo child, so status derives to
    in-progress), and BOARD.md with every region already correct.
    """
    (root / "specs").mkdir(parents=True)
    (root / "specs" / "SPEC-001-x.md").write_text(
        "---\nid: SPEC-001\ntitle: x\nstatus: draft\n---\n\n"
        "<!-- BEGIN:epics (generated by sync — do not edit) -->\n"
        "| Epic | Status | Progress |\n|---|---|---|\n"
        "| EPIC-001 | in-progress | 1/2 done |\n"
        "<!-- END:epics -->\n"
    )
    (root / "EPIC-001-x.md").write_text(
        "---\nid: EPIC-001\ntitle: x\nspec: SPEC-001\nstatus: in-progress\n---\n\n"
        "<!-- BEGIN:children (generated by sync — do not edit) -->\n"
        "| Task | Status | Title |\n|---|---|---|\n"
        "| TASK-001 | done | a |\n"
        "| TASK-002 | todo | b |\n"
        "\n"
        "Progress: 1/2 done\n"
        "<!-- END:children -->\n"
    )
    (root / "TASK-001-x.md").write_text(
        "---\nid: TASK-001\ntitle: a\nstatus: done\nepic: EPIC-001\n"
        "blocked_by: []\nblocks: []\n---\n"
    )
    (root / "TASK-002-x.md").write_text(
        "---\nid: TASK-002\ntitle: b\nstatus: todo\nepic: EPIC-001\n"
        "blocked_by: []\nblocks: []\n---\n"
    )
    (root / "BOARD.md").write_text(
        "# Board\n\n"
        "## Epics\n\n"
        "<!-- BEGIN:epics (generated by sync — do not edit) -->\n"
        "| Epic | Status | Progress |\n|---|---|---|\n"
        "| EPIC-001 | in-progress | 1/2 done |\n"
        "<!-- END:epics -->\n\n"
        "## TODO\n\n"
        "- TASK-002 — b  `EPIC-001`\n"
        "\n"
        "## In Progress\n\n"
        "<!-- BEGIN:in-progress (generated by sync — do not edit) -->\n_(none)_\n<!-- END:in-progress -->\n\n"
        "## In Review\n\n"
        "<!-- BEGIN:in-review (generated by sync — do not edit) -->\n_(none)_\n<!-- END:in-review -->\n\n"
        "## Blocked\n\n"
        "<!-- BEGIN:blocked (generated by sync — do not edit) -->\n_(none)_\n<!-- END:blocked -->\n\n"
        "## Done\n\n"
        "<!-- BEGIN:done (generated by sync — do not edit) -->\n"
        "| Task | Title | Epic | Ref |\n|---|---|---|---|\n"
        "| TASK-001 | a | EPIC-001 | — |\n"
        "<!-- END:done -->\n"
    )


def test_clean_repo_has_no_mismatches(tmp_path):
    write_clean_repo(tmp_path)
    assert compute_mismatches(tmp_path) == []
    assert run_check(tmp_path) == 0


def test_check_writes_no_files(tmp_path):
    write_clean_repo(tmp_path)
    # break something so there's real work for check to (not) do
    board = tmp_path / "BOARD.md"
    board.write_text(board.read_text().replace("1/2 done", "0/2 done"))
    mtimes_before = {p: p.stat().st_mtime_ns for p in tmp_path.rglob("*.md")}
    contents_before = {p: p.read_text() for p in tmp_path.rglob("*.md")}

    exit_code = run_check(tmp_path)

    assert exit_code == 1
    for p in tmp_path.rglob("*.md"):
        assert p.stat().st_mtime_ns == mtimes_before[p]
        assert p.read_text() == contents_before[p]


def test_hand_broken_region_is_detected_with_a_named_diff(tmp_path):
    write_clean_repo(tmp_path)
    board = tmp_path / "BOARD.md"
    broken = board.read_text().replace("1/2 done", "0/2 done")  # one hand-broken char
    board.write_text(broken)

    mismatches = compute_mismatches(tmp_path)
    assert len(mismatches) == 1
    assert mismatches[0].path == board
    assert mismatches[0].region == "epics"
    diff = mismatches[0].diff()
    assert str(board) in diff and "[epics]" in diff
    assert "-| EPIC-001 | in-progress | 0/2 done |" in diff
    assert "+| EPIC-001 | in-progress | 1/2 done |" in diff

    assert run_check(tmp_path) == 1


def test_detects_stale_epic_status_frontmatter(tmp_path):
    write_clean_repo(tmp_path)
    epic = tmp_path / "EPIC-001-x.md"
    epic.write_text(epic.read_text().replace("status: in-progress", "status: todo", 1))
    mismatches = compute_mismatches(tmp_path)
    regions = {m.region for m in mismatches}
    assert "status (frontmatter)" in regions


def test_detects_stale_epic_children_region(tmp_path):
    write_clean_repo(tmp_path)
    epic = tmp_path / "EPIC-001-x.md"
    epic.write_text(epic.read_text().replace("Progress: 1/2 done", "Progress: 0/2 done"))
    mismatches = compute_mismatches(tmp_path)
    assert any(m.region == "children" for m in mismatches)


def test_detects_stale_spec_epics_region(tmp_path):
    write_clean_repo(tmp_path)
    spec = tmp_path / "specs" / "SPEC-001-x.md"
    spec.write_text(spec.read_text().replace("1/2 done", "0/2 done"))
    mismatches = compute_mismatches(tmp_path)
    assert any(m.path == spec and m.region == "epics" for m in mismatches)


def test_detects_a_task_missing_from_its_done_column(tmp_path):
    write_clean_repo(tmp_path)
    board = tmp_path / "BOARD.md"
    text = board.read_text()
    done_region = text[text.index("<!-- BEGIN:done"):text.index("<!-- END:done -->")]
    board.write_text(text.replace(done_region, "<!-- BEGIN:done (generated by sync — do not edit) -->\n_(none)_\n"))
    mismatches = compute_mismatches(tmp_path)
    assert any(m.region == "done" for m in mismatches)


def test_detects_stale_todo_section(tmp_path):
    write_clean_repo(tmp_path)
    board = tmp_path / "BOARD.md"
    board.write_text(board.read_text().replace("- TASK-002 — b  `EPIC-001`\n", ""))
    mismatches = compute_mismatches(tmp_path)
    assert any(m.region == "TODO" for m in mismatches)


def test_detects_stale_blocks_frontmatter(tmp_path):
    write_clean_repo(tmp_path)
    task2 = tmp_path / "TASK-002-x.md"
    task2.write_text(task2.read_text().replace("blocked_by: []", "blocked_by: [TASK-001]"))
    mismatches = compute_mismatches(tmp_path)
    # TASK-001 should now be expected to list TASK-002 in `blocks`
    assert any(m.region == "blocks (frontmatter)" and m.path == tmp_path / "TASK-001-x.md" for m in mismatches)


def test_multiple_mismatches_are_all_reported(tmp_path):
    write_clean_repo(tmp_path)
    board = tmp_path / "BOARD.md"
    board.write_text(board.read_text().replace("1/2 done", "0/2 done"))
    epic = tmp_path / "EPIC-001-x.md"
    epic.write_text(epic.read_text().replace("status: in-progress", "status: todo", 1))
    mismatches = compute_mismatches(tmp_path)
    assert len(mismatches) >= 2
