"""Validates the .tasks/templates/*.md files against SPEC-001's schema
(TASK-002).

Acceptance criteria this covers:
- task.md / epic.md / spec.md frontmatter matches SPEC-001 exactly
- rendering with dummy values parses as valid frontmatter + markdown
- frontmatter keys have zero drift from the documented schema
- body headings match §Data model for task and epic
"""

import re
from pathlib import Path

import pytest

from sync import parse_frontmatter

TEMPLATES = Path(__file__).resolve().parent.parent / ".tasks" / "templates"

# The exact key order SPEC-001 documents for each frontmatter schema.
EXPECTED_KEYS = {
    "task.md": ["id", "title", "type", "status", "epic", "created", "branch", "pr", "merge_commit", "blocked_by", "blocks"],
    "epic.md": ["id", "title", "spec", "status", "created"],
    "spec.md": ["id", "title", "status", "created"],  # no `epics:` field -- that's a generated region
}

# Dummy values substituted for every {{token}} before parsing, so the
# frontmatter is well-formed regardless of which template it came from.
DUMMY_VALUES = {
    "id": "TASK-999",
    "title": "Dummy title: with a colon",
    "type": "feature",
    "epic": "EPIC-999",
    "created": "2026-01-01",
    "branch": "task-999-dummy",
    "blocked_by": "[TASK-001, TASK-002]",
    "spec": "SPEC-999",
}


def render(name: str) -> str:
    """Simulate what a skill does with a template: read the leading doc
    comment for guidance, then use everything from `---` onward as the
    real file content, with every {{token}} filled in. `sync` never
    parses the template file itself -- `discover()` doesn't scan
    `.tasks/templates/` -- so stripping the comment here mirrors real
    usage rather than a production requirement of the template's own
    structure.
    """
    text = (TEMPLATES / name).read_text()
    text = text[text.index("---"):]  # drop the leading <!-- ... --> doc comment

    def substitute(match: re.Match) -> str:
        token = match.group(1)
        if token in DUMMY_VALUES:
            return DUMMY_VALUES[token]
        return "dummy"  # body-prose placeholders (description, goal, criterion, ...)

    return re.sub(r"\{\{(\w+)\}\}", substitute, text)


@pytest.mark.parametrize("name", ["task.md", "epic.md", "spec.md"])
def test_template_exists(name):
    assert (TEMPLATES / name).is_file()


@pytest.mark.parametrize("name", ["task.md", "epic.md", "spec.md"])
def test_rendered_template_parses_as_valid_frontmatter(name):
    fields, body, _order = parse_frontmatter(render(name))
    assert fields["id"] == DUMMY_VALUES["id"]
    assert body.strip() != ""  # has a real markdown body after the frontmatter


@pytest.mark.parametrize("name,expected_keys", EXPECTED_KEYS.items())
def test_frontmatter_keys_match_spec_001_exactly(name, expected_keys):
    _fields, _body, order = parse_frontmatter(render(name))
    assert order == expected_keys


def test_task_template_status_starts_todo_pr_and_merge_commit_null_blocks_empty():
    fields, _body, _order = parse_frontmatter(render("task.md"))
    assert fields["status"] == "todo"
    assert fields["pr"] is None
    assert fields["merge_commit"] is None
    assert fields["blocks"] == []


def test_epic_template_status_starts_todo():
    fields, _body, _order = parse_frontmatter(render("epic.md"))
    assert fields["status"] == "todo"


def test_spec_template_status_starts_draft():
    fields, _body, _order = parse_frontmatter(render("spec.md"))
    assert fields["status"] == "draft"


def test_task_template_body_headings_match_data_model():
    _fields, body, _order = parse_frontmatter(render("task.md"))
    headings = re.findall(r"^## (.+)$", body, re.MULTILINE)
    assert headings == ["Description", "Acceptance criteria", "Testing strategy", "Worklog", "Notes"]


def test_epic_template_body_headings_match_data_model():
    _fields, body, _order = parse_frontmatter(render("epic.md"))
    headings = re.findall(r"^## (.+)$", body, re.MULTILINE)
    assert headings == ["Goal", "In scope", "Out of scope", "Success criteria"]


def test_epic_template_has_an_empty_children_region():
    _fields, body, _order = parse_frontmatter(render("epic.md"))
    assert "<!-- BEGIN:children (generated by sync — do not edit) -->" in body
    assert "_(none)_" in body
    assert "<!-- END:children -->" in body


def test_spec_template_has_an_empty_epics_region():
    _fields, body, _order = parse_frontmatter(render("spec.md"))
    assert "<!-- BEGIN:epics (generated by sync — do not edit) -->" in body
    assert "_(none)_" in body
    assert "<!-- END:epics -->" in body


@pytest.mark.parametrize("name", ["task.md", "epic.md", "spec.md"])
def test_every_placeholder_is_documented_in_the_leading_comment_block(name):
    text = (TEMPLATES / name).read_text()
    comment_block = text[: text.index("-->")]
    tokens = set(re.findall(r"\{\{(\w+)\}\}", text))
    # placeholders that are filled in with real values by a skill/human,
    # not left as body prose slots for the author to write freely
    structural_tokens = tokens & set(DUMMY_VALUES) | ({"blocked_by"} if name == "task.md" else set())
    undocumented = [t for t in structural_tokens if f"{{{{{t}}}}}" not in comment_block]
    assert undocumented == []


def test_epic_children_region_markers_are_real_not_templated():
    # the region markers themselves are literal text, not {{...}} tokens --
    # find_region must locate them even before any placeholder substitution
    from sync import find_region

    raw = (TEMPLATES / "epic.md").read_text()
    assert find_region(raw, "children") is not None
