"""TASK-013: the cross-cutting end-to-end suite over tests/fixtures/mini_repo/.

Acceptance criteria this covers:
- a tests/fixtures/ mini-repo exercising every status, a mixed-children
  epic, a blocked chain, and an archivable task
- idempotency: sync then sync again -> second run empty diff (sync check
  exit 0)
- derivation matrix: one case per row of the worked-cases table, status +
  rule, run through the real pipeline (not just derive_epic_status directly)
- TODO preservation: scrambled order survives, annotations refreshed
- archive test: done/wont-do move, next-id accounts for them

The checked-in fixture is deliberately stale in several places (see its
own BOARD.md) so the first `run_sync` has real, meaningful work to do --
proving the fix, not just an already-clean no-op.
"""

import shutil
from pathlib import Path

import pytest

from sync import compute_mismatches, discover, next_id, run_check, run_sync

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "mini_repo"


@pytest.fixture
def repo(tmp_path):
    shutil.copytree(FIXTURE, tmp_path, dirs_exist_ok=True)
    return tmp_path


# ---------------------------------------------------------------------------
# Idempotency
# ---------------------------------------------------------------------------


def test_first_sync_run_has_real_work_to_do(repo):
    assert compute_mismatches(repo) != []  # the fixture starts deliberately stale


def test_sync_twice_reaches_a_stable_no_op_state(repo):
    first = run_sync(repo)
    assert first != []  # real fixes happened

    second = run_sync(repo)
    assert second == []  # nothing left to do

    assert run_check(repo) == 0
    assert compute_mismatches(repo) == []


# ---------------------------------------------------------------------------
# Derivation matrix, run through the real pipeline end-to-end
# ---------------------------------------------------------------------------


def _tiny_repo(tmp_path, epic_status: str, child_statuses: list[str]) -> Path:
    (tmp_path / "EPIC-001-x.md").write_text(
        f"---\nid: EPIC-001\ntitle: x\nstatus: {epic_status}\n---\n"
        "<!-- BEGIN:children (generated by sync — do not edit) -->\n_(none)_\n<!-- END:children -->\n"
    )
    for i, status in enumerate(child_statuses, start=1):
        (tmp_path / f"TASK-{i:03d}-x.md").write_text(
            f"---\nid: TASK-{i:03d}\ntitle: x\nstatus: {status}\nepic: EPIC-001\n"
            "blocked_by: []\nblocks: []\n---\n"
        )
    (tmp_path / "BOARD.md").write_text(
        "# Board\n\n"
        "## Epics\n\n<!-- BEGIN:epics (generated by sync — do not edit) -->\n_(none)_\n<!-- END:epics -->\n\n"
        "## TODO\n\n\n"
        "## In Progress\n\n<!-- BEGIN:in-progress (generated by sync — do not edit) -->\n_(none)_\n<!-- END:in-progress -->\n\n"
        "## In Review\n\n<!-- BEGIN:in-review (generated by sync — do not edit) -->\n_(none)_\n<!-- END:in-review -->\n\n"
        "## Blocked\n\n<!-- BEGIN:blocked (generated by sync — do not edit) -->\n_(none)_\n<!-- END:blocked -->\n\n"
        "## Done\n\n<!-- BEGIN:done (generated by sync — do not edit) -->\n_(none)_\n<!-- END:done -->\n"
    )
    return tmp_path


@pytest.mark.parametrize(
    "rule,epic_status,child_statuses,expected",
    [
        (1, "wont-do", ["done", "done"], "wont-do"),
        (2, "todo", [], "todo"),
        (2, "todo", ["todo", "todo"], "todo"),
        (3, "todo", ["todo", "in-progress"], "in-progress"),
        (4, "todo", ["blocked", "blocked"], "blocked"),
        (5, "todo", ["wont-do", "wont-do"], "wont-do"),
        (6, "todo", ["done", "wont-do"], "done"),
        (7, "todo", ["todo", "done"], "in-progress"),
    ],
)
def test_derivation_matrix_end_to_end(tmp_path, rule, epic_status, child_statuses, expected):
    _tiny_repo(tmp_path, epic_status, child_statuses)
    run_sync(tmp_path)
    epic = discover(tmp_path)["EPIC-001"]
    assert epic.fields["status"] == expected, f"rule {rule}"
    assert run_check(tmp_path) == 0  # settles immediately, no leftover drift


# ---------------------------------------------------------------------------
# TODO preservation
# ---------------------------------------------------------------------------


def test_todo_scrambled_order_survives_and_annotations_refresh(repo):
    run_sync(repo)
    board = (repo / "BOARD.md").read_text()
    todo_section = board[board.index("## TODO"):board.index("## In Progress")]
    ids = [line.split(" — ")[0].removeprefix("- ") for line in todo_section.splitlines() if line.startswith("- ")]

    # order preserved: TASK-008 before TASK-007 (reverse of id order, as
    # scrambled in the fixture) -- never re-sorted; TASK-003 dropped (its
    # real status is in-progress); TASK-002 appended (was missing)
    assert ids == ["TASK-008", "TASK-007", "TASK-002"]

    lines = {line.split(" — ")[0].removeprefix("- "): line for line in todo_section.splitlines() if line.startswith("- ")}
    assert "TASK-008" in lines["TASK-007"] and "⛔" in lines["TASK-007"]  # still-todo blocker shown
    assert "⛔" not in lines["TASK-008"]  # its blocker (TASK-001) is done -- refreshed, not stale
    assert "`EPIC-001`" not in lines["TASK-008"]  # TASK-008 has no epic -- stale tag from the fixture is gone
    assert "`EPIC-001`" in lines["TASK-002"]  # TASK-002's real epic tag is present


# ---------------------------------------------------------------------------
# Archiving
# ---------------------------------------------------------------------------


def test_archive_moves_done_and_wont_do_and_next_id_accounts_for_them(repo):
    run_sync(repo)

    assert (repo / "archive" / "TASK-001-x.md").is_file()
    assert (repo / "archive" / "TASK-006-x.md").is_file()
    assert not (repo / "TASK-001-x.md").exists()
    assert not (repo / "TASK-006-x.md").exists()

    assert next_id(repo, "task") == "TASK-009"  # accounts for the 8 that exist, 6 archived or not
