"""Unit tests for `.tasks/bin/sync`'s write mode (TASK-013): apply_all,
run_sync, and load_config.

Built because TASK-013's own idempotency test ("run sync, then sync
again, confirm the second run is a no-op") has no way to exist without
something that actually writes -- deliberately deferred out of TASK-011
and TASK-012 until it became unavoidable here.
"""

from pathlib import Path

from sync import apply_all, compute_mismatches, load_config, run_sync, should_auto_archive
from test_sync_check import write_clean_repo


# ---------------------------------------------------------------------------
# apply_all
# ---------------------------------------------------------------------------


def test_apply_all_on_a_clean_repo_changes_nothing(tmp_path):
    write_clean_repo(tmp_path)
    assert apply_all(tmp_path) == []
    assert compute_mismatches(tmp_path) == []


def test_apply_all_fixes_a_stale_region_and_settles_clean(tmp_path):
    write_clean_repo(tmp_path)
    board = tmp_path / "BOARD.md"
    board.write_text(board.read_text().replace("1/2 done", "0/2 done"))
    assert compute_mismatches(tmp_path)  # confirm it's actually stale first

    changed = apply_all(tmp_path)

    assert changed == [board]
    assert compute_mismatches(tmp_path) == []


def test_apply_all_fixes_stale_epic_status_and_stale_spec_region_together(tmp_path):
    write_clean_repo(tmp_path)
    epic = tmp_path / "EPIC-001-x.md"
    epic.write_text(epic.read_text().replace("status: in-progress", "status: todo", 1))

    changed = apply_all(tmp_path)

    assert epic in changed
    assert compute_mismatches(tmp_path) == []


def test_apply_all_chains_multiple_stale_regions_in_the_same_file(tmp_path):
    # A naive "diff each region against the pristine original, then write
    # each independently" approach would let a later write undo an
    # earlier one, since both diffs are computed against the same stale
    # starting text. Break both the epics panel AND the done column in
    # BOARD.md at once and confirm apply_all fixes both, not just one.
    write_clean_repo(tmp_path)
    board = tmp_path / "BOARD.md"
    text = board.read_text()
    text = text.replace("1/2 done", "0/2 done")  # breaks the epics panel
    done_region = text[text.index("<!-- BEGIN:done"):text.index("<!-- END:done -->")]
    text = text.replace(done_region, "<!-- BEGIN:done (generated by sync — do not edit) -->\n_(none)_\n")
    board.write_text(text)
    assert len(compute_mismatches(tmp_path)) == 2  # both broken

    apply_all(tmp_path)

    final = board.read_text()
    assert "1/2 done" in final  # epics panel fixed
    assert "TASK-001" in final[final.index("## Done"):]  # done column fixed too
    assert compute_mismatches(tmp_path) == []


def test_apply_all_does_not_archive(tmp_path):
    write_clean_repo(tmp_path)
    apply_all(tmp_path)
    assert not (tmp_path / "archive").exists()


# ---------------------------------------------------------------------------
# run_sync (apply_all + conditional archive)
# ---------------------------------------------------------------------------


def test_run_sync_is_a_true_no_op_once_settled(tmp_path):
    write_clean_repo(tmp_path)
    run_sync(tmp_path)  # first call has real archiving work (TASK-001 is done)
    assert run_sync(tmp_path) == []  # second call: nothing left to do


def test_run_sync_archives_done_tasks_by_default(tmp_path):
    write_clean_repo(tmp_path)  # TASK-001 is done, not yet archived
    changed = run_sync(tmp_path)
    assert (tmp_path / "archive" / "TASK-001-x.md").is_file()
    assert (tmp_path / "archive" / "TASK-001-x.md") in changed


def test_run_sync_skips_archiving_when_config_says_so(tmp_path):
    write_clean_repo(tmp_path)
    (tmp_path / "config.md").write_text("---\narchive_done: false\n---\n")
    run_sync(tmp_path)
    assert (tmp_path / "TASK-001-x.md").is_file()
    assert not (tmp_path / "archive").exists()


def test_run_sync_twice_is_idempotent(tmp_path):
    write_clean_repo(tmp_path)
    board = tmp_path / "BOARD.md"
    board.write_text(board.read_text().replace("1/2 done", "0/2 done"))

    first = run_sync(tmp_path)
    assert first  # had real work to do
    second = run_sync(tmp_path)

    assert second == []
    assert compute_mismatches(tmp_path) == []


# ---------------------------------------------------------------------------
# load_config
# ---------------------------------------------------------------------------


def test_load_config_missing_file_returns_empty_dict(tmp_path):
    assert load_config(tmp_path) == {}


def test_load_config_parses_real_fields(tmp_path):
    (tmp_path / "config.md").write_text("---\narchive_done: false\ntest_command: pytest\n---\n")
    config = load_config(tmp_path)
    assert config == {"archive_done": False, "test_command": "pytest"}


def test_load_config_feeds_should_auto_archive(tmp_path):
    (tmp_path / "config.md").write_text("---\narchive_done: false\n---\n")
    assert should_auto_archive(load_config(tmp_path)) is False
